(define (x) (display "Start Transation (exit with 0):") (newline) (register -1 0))

(define (register i t)
	(cond ((zero? i) 
		(newline)
		(display "Final Subtotal: ")
		(display t)
		(newline)
		(display "Tax: ")
		(display (* t 0.065))
		(newline)
		(display "Total: ")
		(display (* t 1.065)) #t)
	(else 
		(newline)
		(display "Subtotal: ")
		(display t)
		(newline)
		(let ((i (read))) (register i (+ t i)))
	)
	)
)
